site_name: Extração de dados
repo_url: https://github.com/CarduCaldeira/template-python-postgres
docs_dir: docs/
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: 'indigo'
      accent: 'indigo'
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: 'indigo'
      accent: 'indigo'
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - toc.integrate
    - content.code.annotate
    - content.tabs.link
    - search.highlight
    - search.share
    - header.autohide
    - header.sticky
    - navigation.tracking
    - mode-toggle
  language: pt-BR

plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: [source]

markdown_extensions:
  - pymdownx.tasklist  # Lista de tarefas
  - pymdownx.emoji  # Emojis
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight
