services:
  db:
    image: postgres
    container_name: postgres_container_app
    restart: unless-stopped
    env_file: ./envs/db.env
    ports:
      - "5432:5432"
    volumes:
      - ./../data/pgdata:/var/lib/postgresql/data/pgdata # onde é salvo o banco
      #- ./files:/home #no caso de precisar dar carga a partir de csv por exemplo colcar em files/
      - ./../data/start.sql:/docker-entrypoint-initdb.d/start.sql #script que sera executado quando o container for executado
    networks:
      - pg_network
      
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container_app
    restart: always
    env_file: ./envs/pgadmin.env
    ports:
      - "8891:0080"
    volumes:
      - ./../data/pgadmin:/var/lib/pgadmin
    user: "${UID}:${GID}" 
    networks:
      - pg_network
    
  python-project:
    depends_on:
      - db
    image: poetry_image
    container_name: poetry_container_app
    hostname: docker
    tty: true
    command: ["/bin/bash"]
    build:
      context: .
      args:
        GROUP_ID: ${GROUP_ID}
        USER_ID: ${USER_ID}
        USER_NAME: myuser
        WORK_DIR:  /home/myuser/PROJECT
    env_file: ./envs/python_project.env
    volumes:
      - type: bind
        source: ./..
        target: /home/myuser/PROJECT
      - type: bind
        source: ./../ignorefolder
        target: /home/myuser/PROJECT/data
    ports:
      - "8000:8000"
    networks:
      - pg_network
  
networks:
  pg_network:
    driver: bridge
  
  #docker exec -it local_pgdb psql -U user-name -d postgres
  
  #./pgadmin/storage/user-name_domain-name.com/

